version: "3"

services:
  server:
    image: node
    restart: always
    build: ./server
    networks:
      app:
        ipv4_address: 172.16.100.100
  web:
    image: nginx
    restart: always
    build: ./web
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    volumes:
      - ./web/ssl:/etc/nginx/conf.d/ssl
    environment:
      NGINX_HOST: server.websocket-online-test.flxxyz.com
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/site.conf && exec nginx -g 'daemon off;'"
    networks:
      app:
        ipv4_address: 172.16.100.101

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24
